name: kazoo-configs-couchdb
custom_files: null
exposure: private
base_branch: origin/5.3
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-couchdb
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Kazoo specific configuration for CouchDB'
    description: |
      A clustered fault-tolerant database which provides the
      persistent data store service for the Kazoo platform.
      This package contains the base configuration for the
      service. If you need help you can contact us via the
      dev mailing list or on IRC at #2600hz on FreeNode.
    dist: .el7.centos
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r couchdb %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/couchdb

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/rsyslog.d
      rm -rf system/rsyslog.d/1-default-config-override.conf
      rm -rf system/rsyslog.d/5-rate-limits.conf
      cp -r  system/rsyslog.d/*.conf %{buildroot}/etc/rsyslog.d

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        -
          mode: noreplace
          path: /etc/kazoo/couchdb
        -
          mode: noreplace
          path: '/etc/rsyslog.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/logrotate.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/security/limits.d/*couchdb*'
      path:
        - /usr/sbin/kazoo-couchdb
        - /usr/lib/systemd/system/kazoo-couchdb.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
  rockylinux8:
    name: kazoo-configs-couchdb
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Kazoo specific configuration for CouchDB'
    description: |
      A clustered fault-tolerant database which provides the
      persistent data store service for the Kazoo platform.
      This package contains the base configuration for the
      service. If you need help you can contact us via the
      dev mailing list or on IRC at #2600hz on FreeNode.
    dist: .el8
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r couchdb %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/couchdb

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/rsyslog.d
      rm -rf system/rsyslog.d/1-default-config-override.conf
      rm -rf system/rsyslog.d/5-rate-limits.conf
      cp -r  system/rsyslog.d/*.conf %{buildroot}/etc/rsyslog.d

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        -
          mode: noreplace
          path: /etc/kazoo/couchdb
        -
          mode: noreplace
          path: '/etc/rsyslog.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/logrotate.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/security/limits.d/*couchdb*'
      path:
        - /usr/sbin/kazoo-couchdb
        - /usr/lib/systemd/system/kazoo-couchdb.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
  rockylinux9:
    name: kazoo-configs-couchdb
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Kazoo specific configuration for CouchDB'
    description: |
      A clustered fault-tolerant database which provides the
      persistent data store service for the Kazoo platform.
      This package contains the base configuration for the
      service. If you need help you can contact us via the
      dev mailing list or on IRC at #2600hz on FreeNode.
    dist: .el9
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r couchdb %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/couchdb

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/rsyslog.d
      rm -rf system/rsyslog.d/1-default-config-override.conf
      rm -rf system/rsyslog.d/5-rate-limits.conf
      cp -r  system/rsyslog.d/*.conf %{buildroot}/etc/rsyslog.d

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        -
          mode: noreplace
          path: /etc/kazoo/couchdb
        -
          mode: noreplace
          path: '/etc/rsyslog.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/logrotate.d/*couchdb*'
        -
          mode: noreplace
          path: '/etc/security/limits.d/*couchdb*'
      path:
        - /usr/sbin/kazoo-couchdb
        - /usr/lib/systemd/system/kazoo-couchdb.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-couchdb
    package: kazoo-configs-couchdb
    type: required
    branch: '5.3'
dependencies: null
